/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fulladder_1 (
    input a,
    input b,
    input cIn,
    output reg sum,
    output reg cOut
  );
  
  
  
  always @* begin
    sum = 1'h0;
    cOut = 1'h0;
    if (a + b + cIn == 1'h0) begin
      sum = 1'h0;
      cOut = 1'h0;
    end
    if (a + b + cIn == 1'h1) begin
      sum = 1'h1;
      cOut = 1'h0;
    end
    if (a + b + cIn == 2'h2) begin
      sum = 1'h0;
      cOut = 1'h1;
    end
    if (a + b + cIn == 2'h3) begin
      sum = 1'h1;
      cOut = 1'h1;
    end
  end
endmodule
