/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_2 (
    input [3:0] char,
    output reg [6:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h1: begin
        segs = 7'h73;
      end
      2'h2: begin
        segs = 7'h71;
      end
      default: begin
        segs = 7'h00;
      end
    endcase
  end
endmodule
